### PR TITLE
Reporting updates

### PR DESCRIPTION
**Pull request by cyocum**
This does some general refactoring and may make things a bit easier to read in places.  This is a first stab at it. Let me know what you think.

### CODE REVIEW

**Review by Thegaram — APPROVED** [review]
Thanks @cyocum, I wanted to fix your suggestions myself, thanks for taking on the task.

Everything seems alright. One suggestion for the `Reporting` readability problem:

```ocaml
let stats = [
  ("passed",    Outcome.count_passed outcomes);
  ("pending",   Outcome.count_pending outcomes);
  ("skipped",   Outcome.count_skipped outcomes);
  ("undefined", Outcome.count_undefined outcomes);
  ("failed",    Outcome.count_failed outcomes);
] in

let formattedStats = Base.List.fold stats ~init:[]  ~f:(fun acc (text, count) ->
  if count > 0
  then (string_of_int count ^ " " ^ text) :: acc
  else acc
) in
...
```

Feel free to use this if you think this expresses the intent of the code more clearly.

When I build in a clean repo I get a warning, I am not sure what causes this:

```
ocamlfind opt -c -I lib/ -for-pack Cucumber -package re,re.perl,base -c lib/location.mli lib/docstring.mli lib/table.ml lib/step.mli lib/outcome.mli lib/pickle.mli lib/report.mli lib/lib.mli
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Location, and its interface was not compiled with -opaque
```

Also, you may want to consider enabling trailing whitespace trimming in your editor.

**Comment by Thegaram** [comment]
Thanks @cyocum, I wanted to fix your suggestions myself, thanks for taking on the task.

Everything seems alright. One suggestion for the `Reporting` readability problem:

```ocaml
let stats = [
  ("passed",    Outcome.count_passed outcomes);
  ("pending",   Outcome.count_pending outcomes);
  ("skipped",   Outcome.count_skipped outcomes);
  ("undefined", Outcome.count_undefined outcomes);
  ("failed",    Outcome.count_failed outcomes);
] in

let formattedStats = Base.List.fold stats ~init:[]  ~f:(fun acc (text, count) ->
  if count > 0
  then (string_of_int count ^ " " ^ text) :: acc
  else acc
) in
...
```

Feel free to use this if you think this expresses the intent of the code more clearly.

When I build in a clean repo I get a warning, I am not sure what causes this:

```
ocamlfind opt -c -I lib/ -for-pack Cucumber -package re,re.perl,base -c lib/location.mli lib/docstring.mli lib/table.ml lib/step.mli lib/outcome.mli lib/pickle.mli lib/report.mli lib/lib.mli
File "_none_", line 1:
Warning 58: no cmx file was found in path for module Location, and its interface was not compiled with -opaque
```

Also, you may want to consider enabling trailing whitespace trimming in your editor.

**Comment by cyocum** [comment]
I apologise.  I should have waited for you.  Thank you for your suggestion.  I will take that in and return for another review.

I know about the warning.  I am not sure where it is coming from either.  I will see if I can squash it in his pull request.

I will add a before-save hook into Emacs so it will strip trailing whitespace.  Thanks!

**Comment by cyocum** [comment]
@Thegaram would you mind having a look at this again?  I will have a look at the other issues you identified in another branch.  Thanks!

**Pull request merged**
