### PR TITLE
Cmdliner

### PR DESCRIPTION
**Pull request by cyocum**
Updated the command line parsing to use Cmdliner.  This will get rid of the mutable variables and make the process cleaner.  However, it does make the system produce an error message on failure of scenarios.

### CODE REVIEW

**Comment by Thegaram** [comment]
```
$ make build_test
ocamlfind opt -g -package re,re.perl,cmdliner,cucumber,base -linkpkg -cclib -lgherkin -o cucumber_run test/test.ml 
File "test/test.ml", line 68, characters 7-33:
Error: This expression has type unit but an expression was expected of type
         int
make: *** [build_test] Error 2
```

**Comment by cyocum** [comment]
Good catch. There is always something :smile:

**Review by Thegaram — CHANGES_REQUESTED** [review]
Seems good! Test execution is reversed again.

```
$ ./cucumber_run test1.feature test2.feature
...
Feature File: test2.feature
3 scenarios (1 undefined, 2 passed)
9 steps (1 undefined, 2 skipped, 6 passed)
...U--...

...
Feature File: test1.feature
3 scenarios (1 undefined, 2 passed)
9 steps (1 undefined, 2 skipped, 6 passed)
...U--...

Cucumber.ml: Some scenarios failed. Please see output for more details
```

**Comment by cyocum** [comment]
Great.  Thanks. It seems that reversed lists will always be my bugbear.  Let me know what you think. If you are happy then I am happy to merge.

**Review by Thegaram — APPROVED** [review]

**Pull request merged**
