### PR TITLE
Before and After hooks

### PR DESCRIPTION
**Pull request by cyocum**
Added a basic facility to run before and after hooks.

### CODE REVIEW

**Review by Thegaram — COMMENTED** [review]
So basically it only makes sense to use this kind of before/after hooks when they're not pure, i.e. they log something, modify global state, etc, right? Can you give me a use case for using such hooks when the step definitions pass state between each other? I'm thinking about the usefulness of passing an *initial state* from the before hooks, not sure if it would be useful or not.

It seems a bit dangerous that, for before and after hooks (vs. step definitions), the order of declaration matters, i.e. they're executed in that order. It might be the same behavior in other Cucumber implementations too though, and I think most people would only use one of these hooks.

The code looks good. Could you extend the test file with some examples of before/after hooks?

**Comment by cyocum** [comment]
The use case is to have feature parity with other Cucumber implementations (see [here](https://github.com/cucumber/cucumber/wiki/Hooks)).  I want Cucumber users from other languages to have everything they would expect to have in Cucumber available to them.  I would normally use a Given step to create initial state that would then cascade down the scenario.

**Comment by cyocum** [comment]
@Thegaram I am just checking as I am unclear but is it alright if I merge these changes or would you like more information?

**Comment by Thegaram** [comment]
The line

```ocaml
let (>>=) = Base.Option.(>>=)
```

Seems to be unused. Apart from this everything seems okay, feel free to merge it.

**Pull request merged**
